### PR TITLE
Zerubabel4

### PR DESCRIPTION
**Pull request by zerubabel4**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Comment by alexanderism55** [comment]
@zerubabel4 Listen mention one of the coaches here

**Comment by zerubabel4** [comment]
@colevandersWands @bermarte @danielhalasz hello i need help with 
> markdownlint --ignore node_modules --config ./.markdownlint.jsonc --fix ./ 
there is an error and i'm struggling.

**Comment by danielhalasz** [comment]
@zerubabel4 looks like you haven't run `npm run format` yet

**Comment by zerubabel4** [comment]
> @zerubabel4 looks like you haven't run `npm run format` yet

@danielhalasz  did but it's still not working

**Comment by danielhalasz** [comment]
@zerubabel4 ok, so inspecting the error message you can see that it is because you are using HTML inside the markdown. that is usually not recommended, although technically possible..please remove it and run the test again locally to see if it solves the errors.

**Comment by danielhalasz** [comment]
```student-bios/zerubabel4.md:1:1 MD033/no-inline-html Inline HTML [Element: h1]
student-bios/zerubabel4.md:3:1 MD033/no-inline-html Inline HTML [Element: div]
student-bios/zerubabel4.md:7:1 MD033/no-inline-html Inline HTML [Element: h2]
student-bios/zerubabel4.md:21:1 MD033/no-inline-html Inline HTML [Element: h1]
student-bios/zerubabel4.md:37:1 MD033/no-inline-html Inline HTML [Element: h2]
student-bios/zerubabel4.md:48:1 MD033/no-inline-html Inline HTML [Element: em]```

**Comment by bermarte** [comment]
@zerubabel4 There are still conflicts and linting's problems still open, it's worth trying to fix them.

**Comment by bermarte** [comment]
@zerubabel4 There are still some problems open

**Review by danielhalasz — CHANGES_REQUESTED** [review]
see comments

**Comment by zerubabel4** [comment]
@bermarte @danielhalasz sorry for the late reply, i think i should delete the links.

**Comment by zerubabel4** [comment]
i am trying to delete this pull request b/c i already did my md and it's merged.

**Pull request closed without merging**
