### PR TITLE
Haneefa123 branch pull request

### PR DESCRIPTION
**Pull request by Haneefa-Shaik**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Comment by Haneefa-Shaik** [comment]
closing this pull request

**Comment by danielhalasz** [comment]
@Haneefa-Shaik all looks good, but please do a `git pull origin main` and push again so that you are on the latest version of the team repo

**Comment by Haneefa-Shaik** [comment]
Hello @danielhalasz. Resolved merge conflict. Thank you

**Review by danielhalasz — CHANGES_REQUESTED** [review]
looks great, just please move the image file into `student-bios/assets` folder

**Comment by Haneefa-Shaik** [comment]
@danielhalasz  I moved the image file into student-bios/assets folder. Thank you

**Comment by danielhalasz** [comment]
almost there @Haneefa-Shaik , looks good, but please do a `git pull origin main` and push again so that you are on the latest version of the team repo

**Comment by Haneefa-Shaik** [comment]
@danielhalasz Done .

**Comment by danielhalasz** [comment]
image

what would be ideal is to have only your files in the PR, the md and the images and nothing else. can you try to do that?

**Pull request closed without merging**
