### PR TITLE
Hadoan149: student bio

### PR DESCRIPTION
**Pull request by hadoan149**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Comment by talmurshidi** [comment]
Hello @hadoan149 , very good job.
I have some notes:

1. Add `Projects`, `Milestone` and create an issue `Hadoan: Create student bio` then assign it to the current Pull Request (PR).
2. Change the title of PR to something like `Hadoan: student bio`.
3. Make sure that you have the last version using command `git pull origin main` .
4. Change .md file to your Github account name `hadoan149`.
5. When I run `npm run lint:md` it shows `student-bios/hadoan.md:3 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]` and that is means you have to change `###` into `##` or add welcome sentence with `##`.

@danielhalasz , quick question:
When I run `npm run format` it changes 79 files and this is strange. 
What do you think?

**Comment by danielhalasz** [comment]
@talmurshidi I have checked out this branch and if I run `npm run format` and then `git status`, it only changes 2 files:
    modified:   student-bios/hadoan.md
        modified:   student-bios/hadoan149.md

**Comment by talmurshidi** [comment]
@danielhalasz , you are write.
I think this happed because I changed the configuration of Prettier to fit with my code style and work :)

**Comment by hadoan149** [comment]
Hi @danielhalasz and @talmurshidi it seems like I failed the linting test. When I ran `npm run lint:md`, it showed:
> school-as-code@1.0.0 lint:md
> markdownlint --ignore node_modules --config ./.markdownlint.jsonc --fix ./

Not sure where the problem is :/ Thank you in advance!

**Comment by talmurshidi** [comment]
@hadoan149 ,you should run linting one by one and you forgot:
`npm run format` then `npm run format:check`
After using the above commands the problem should be fixed.

**Review by danielhalasz — APPROVED** [review]

**Pull request merged**
