### PR TITLE
Haneefa: Student bio

### PR DESCRIPTION
**Pull request by Haneefa-Shaik**
### General Checks

- [X] the branch is up to date with `main`/`master`
- [X] the code works when pulled and run locally
- [X] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Comment by Haneefa-Shaik** [comment]
@danielhalasz As per your comment, I Just pushed only the requested file. Can you check and review please?

**Comment by talmurshidi** [comment]
@Haneefa-Shaik , very good job.
Some notes:

1. The title of PR could be `Haneefa: Student bio` is more clear and descriptive.
2. Make sure to add `Projects`, `Milestone` and link the issue.

**Comment by Haneefa-Shaik** [comment]
Thank you @talmurshidi for your valuable suggestions and i did them.

**Comment by talmurshidi** [comment]
@Haneefa-Shaik, very good.
Maybe you forget to change the path of the photo because it is not working in your [bio file](https://github.com/lab-brussels-1/home/blob/HaneefaNew/student-bios/Haneefa-Shaik.md)
This is the correct path `Haneefa`
Also do not forget to create an issue and link it to this repository and its name could be `Haneefa: Create student bio` and you can write some details and description for it.

**Comment by Haneefa-Shaik** [comment]
#171 fixed

**Review by talmurshidi — APPROVED** [review]
Very good job, well done.

**Pull request merged**
